# Generated by Django 4.2 on 2026-05-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_connection_at',
            field=models.DateTimeField(blank=True, help_text='Date et heure de la dernière connexion réussie', null=True, verbose_name='Dernière connexion'),
        ),
    ]
