# Generated by Django 4.2 on 2026-05-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_last_connection_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text="Image de profil de l'utilisateur", null=True, upload_to='profile_pictures/%Y/%m/', verbose_name='Photo de profil'),
        ),
    ]
