# Generated by Django 4.2 on 2026-05-05 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_nom_prenom_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='description',
        ),
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.TextField(blank=True, verbose_name='Adresse physique'),
        ),
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email officiel'),
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_id',
            field=models.CharField(blank=True, help_text='Numéro de registre de commerce (privé) ou décret (public)', max_length=100, null=True, verbose_name='Identifiant légal (RC/ICE/Décret)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='org_logos/%Y/%m/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Organisation de niveau supérieur (pour hiérarchie publique)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounts.organization', verbose_name='Organisation parente'),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('PRIVATE', 'Cabinet Privé / Entreprise'), ('PUBLIC', 'Entité Publique / Administration')], default='PRIVATE', max_length=10, verbose_name="Type d'organisation"),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, verbose_name='Site web'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'adhésion"),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Propriétaire / Chef de service'), ('ADMIN', 'Administrateur'), ('MANAGER', 'Gestionnaire'), ('USER', 'Utilisateur')], default='USER', max_length=10, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='code',
            field=models.CharField(db_index=True, help_text="Code unique identifiant l'organisation", max_length=50, unique=True, verbose_name='Code Organisation'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, verbose_name="Nom de l'organisation"),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['type'], name='accounts_or_type_b41862_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['code'], name='accounts_or_code_ccebb6_idx'),
        ),
    ]
