# Generated by Django 4.2 on 2026-05-07 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_organization_description_organization_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text="Date et heure de la suppression logique de l'organisation", null=True, verbose_name='Date de suppression'),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text="Indique si l'organisation a été supprimée logiquement (soft delete). Ne plus l'afficher dans l'application.", verbose_name='Supprimée (logique)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.TextField(blank=True, help_text="Adresse postale complète de l'organisation", verbose_name='Adresse physique'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='code',
            field=models.CharField(db_index=True, help_text="Code unique d'identification de l'organisation (ex: CAB-001, DIR-FIN)", max_length=50, unique=True, verbose_name='Code Organisation'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text="Date et heure de création de l'organisation dans le système", verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant créé cette organisation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, help_text='Adresse email principale pour les communications officielles', max_length=254, verbose_name='Email officiel'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Indique si l'organisation est active et accessible dans le système", verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='legal_id',
            field=models.CharField(blank=True, help_text='Numéro de registre de commerce pour les privés ou numéro de décret pour les publics', max_length=100, null=True, verbose_name='Identifiant légal (RC/ICE/Décret)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, help_text="Image du logo de l'organisation (formats: PNG, JPG)", null=True, upload_to='org_logos/%Y/%m/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text="Nom officiel ou raison sociale de l'organisation", max_length=255, verbose_name="Nom de l'organisation"),
        ),
        migrations.AlterField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Organisation de niveau supérieur dans la hiérarchie (ex: Ministère pour une Direction)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounts.organization', verbose_name='Organisation parente'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, help_text='Numéro de téléphone principal de contact', max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('PRIVATE', 'Cabinet Privé / Entreprise'), ('PUBLIC', 'Entité Publique / Administration')], default='PRIVATE', help_text='Catégorie : Cabinet privé/entreprise ou entité publique/administration', max_length=10, verbose_name="Type d'organisation"),
        ),
        migrations.AlterField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification des informations', verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, help_text="URL du site internet de l'organisation", verbose_name='Site web'),
        ),
    ]
