# Generated by Django 4.2 on 2026-05-07 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_organization_deleted_at_organization_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant effectué la dernière modification de cette organisation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
    ]
