# Generated by Django 4.2 on 2026-05-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_organization_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_test_data',
            field=models.BooleanField(default=False, help_text='Indique si cette organisation est une donnée de test (True) ou réelle (False)', verbose_name='Données de test'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_test_data'], name='accounts_or_is_test_a2c866_idx'),
        ),
    ]
