# Generated by Django 4.2 on 2026-06-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_migrate_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text="Indique si l'utilisateur a été supprimé logiquement", verbose_name='Supprimé (logique)'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('ROLE_ORGANISATION_ADMIN', 'Responsable Admin'), ('ROLE_ORGANISATION_AGENT', 'Agent')], default='ROLE_ORGANISATION_AGENT', max_length=30, verbose_name='Rôle'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='accounts_cu_email_5ce40b_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_deleted'], name='accounts_cu_is_dele_643a07_idx'),
        ),
    ]
