# Generated by Django 4.2 on 2026-06-25 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_add_customuser_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='nom_societe',
        ),
    ]
