# Generated by Django 4.2 on 2026-06-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_nom_societe'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nom_societe',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
