# Generated by Django 4.2 on 2026-06-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_customuser_nom_societe'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='platform_role',
            field=models.CharField(blank=True, choices=[('ROLE_APP_ADMIN', 'Admin App')], default=None, max_length=30, null=True, verbose_name='Rôle plateforme'),
        ),
    ]
