# Generated by Django 4.2.30 on 2026-07-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_rename_role_app_admin_to_role_admin_systeme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='platform_role',
            field=models.CharField(blank=True, choices=[('ROLE_ADMIN_SYSTEME', 'Admin Système')], help_text="Rôle global sur la plateforme (hors organisations). ROLE_ADMIN_PLATEFORME pour les admins d'application.", max_length=30, null=True, verbose_name='Rôle plateforme'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('ROLE_ORGANISATION_ADMIN', 'Admin Organisation'), ('ROLE_ORGANISATION_AGENT', 'Agent Organisation')], default='ROLE_ORGANISATION_AGENT', max_length=30, verbose_name='Rôle'),
        ),
    ]
