# Generated by Django 4.2.30 on 2026-07-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_customuser_platform_role_alter_membership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='piece_sort_config',
            field=models.JSONField(blank=True, default=dict, help_text='Champ de tri par défaut par type de pièce (tableaux de données).', verbose_name='Tri par défaut des tableaux de pièces'),
        ),
    ]
