# Generated by Django 4.2.30 on 2026-07-18 17:12

import copy

import accounts.piece_defaults
from accounts.piece_defaults import DEFAULT_PIECE_SORT_CONFIG
from django.db import migrations, models


def seed_existing_users(apps, schema_editor):
    """Applique la configuration de tri de référence à TOUS les comptes existants qui n'en
    ont pas déjà une (opérateurs, admins d'organisation, admins d'app, super admin).

    Non destructif : les comptes ayant déjà une configuration personnalisée sont laissés
    intacts (« par défaut » ≠ écrasement d'un choix explicite). Le compte de référence
    « agent1@sdgps.ma » possède déjà cette configuration : il n'est donc pas modifié.
    """
    User = apps.get_model('accounts', 'CustomUser')
    for user in User.objects.all().iterator():
        if not user.piece_sort_config:
            user.piece_sort_config = copy.deepcopy(DEFAULT_PIECE_SORT_CONFIG)
            user.save(update_fields=['piece_sort_config'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_customuser_piece_fields_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='piece_sort_config',
            field=models.JSONField(blank=True, default=accounts.piece_defaults.default_piece_sort_config, help_text='Champ de tri par défaut par type de pièce (tableaux de données).', verbose_name='Tri par défaut des tableaux de pièces'),
        ),
        migrations.RunPython(seed_existing_users, migrations.RunPython.noop),
    ]
