# Generated by Django 4.2.30 on 2026-07-18 19:29

import accounts.piece_defaults
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_customuser_piece_sort_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='piece_fields_config',
            field=models.JSONField(blank=True, default=accounts.piece_defaults.default_piece_fields_config, help_text='Colonnes affichées (et leur ordre) par type de pièce et par vue (app / rapport PDF).', verbose_name='Champs par défaut des tableaux de pièces'),
        ),
    ]
