# Generated by Django 4.2.30 on 2026-07-19 16:16

import accounts.piece_defaults
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_customuser_piece_fields_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ssdgps_sort_config',
            field=models.JSONField(blank=True, default=accounts.piece_defaults.default_ssdgps_sort_config, help_text='Niveaux de tri (champ + sens) par défaut du tableau de la liste des SSDGPS.', verbose_name='Tri multi-niveaux de la liste des SSDGPS'),
        ),
    ]
