# Generated by Django 4.2.30 on 2026-07-25 23:36

import accounts.piece_defaults
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_fix_agent_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='org_sort_config',
            field=models.JSONField(blank=True, default=accounts.piece_defaults.default_org_sort_config, help_text='Niveaux de tri (champ + sens) par défaut du tableau de la liste des organisations.', verbose_name='Tri multi-niveaux de la liste des organisations'),
        ),
    ]
