# Generated by Django 4.2.30 on 2026-07-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_customuser_organisme_sort_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='table_sort_configs',
            field=models.JSONField(blank=True, default=dict, help_text='Niveaux de tri (champ + sens) par défaut, par tableau, pour les listes génériques.', verbose_name='Tri multi-niveaux par tableau (générique)'),
        ),
    ]
