# Generated by Django 4.2.30 on 2026-07-26 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_customuser_table_columns_configs'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant créé ce compte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant supprimé (logiquement) ce compte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_users', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification de la fiche utilisateur', verbose_name='Modifié le'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant effectué la dernière modification de ce compte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_users', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.AddField(
            model_name='organization',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant supprimé (logiquement) cette organisation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text="Date et heure de la suppression logique de l'utilisateur", null=True, verbose_name='Supprimé le'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text="Indique si l'utilisateur a été supprimé logiquement", verbose_name='Supprimé'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text="Date et heure de création de l'organisation dans le système", verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text="Date et heure de la suppression logique de l'organisation", null=True, verbose_name='Supprimé le'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text="Indique si l'organisation a été supprimée logiquement (soft delete). Ne plus l'afficher dans l'application.", verbose_name='Supprimé'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification des informations', verbose_name='Modifié le'),
        ),
    ]
