
from django.core.management.base import BaseCommand
from accounts.models import Organization
from django.utils import timezone


class Command(BaseCommand):
    help = 'Crée 20 organisations de démo avec des profils variés'

    def handle(self, *args, **options):
        Organization.objects.test_data_only().delete()

        orgs = [
            # ===== PRIVÉ (10) =====
            {
                'code': 'DEMO-NOVA-01',
                'name': 'NovaTech Solutions',
                'type': 'PRIVATE',
                'legal_id': 'RC-45231-CAS',
                'address': '127 Boulevard Anfa, 20e étage, Casablanca 20000',
                'phone': '+212 5 22 45 67 89',
                'email': 'contact@novatech.ma',
                'website': 'https://www.novatech.ma',
                'is_active': True,
            },
            {
                'code': 'DEMO-LEX-02',
                'name': 'LexConsult Associés',
                'type': 'PRIVATE',
                'legal_id': 'RC-31897-RBA',
                'address': '33 Avenue Mohamed V, Bureau 402, Rabat 10000',
                'phone': '+212 5 37 70 12 34',
                'email': 'cabinet@lexconsult.ma',
                'website': 'https://www.lexconsult.ma',
                'is_active': True,
            },
            {
                'code': 'DEMO-BATI-03',
                'name': 'Bâtir & Co – Groupe Immobilier',
                'type': 'PRIVATE',
                'legal_id': 'RC-67123-MRK',
                'address': 'Zone Industrielle Sidi Ghanem, Marrakech 40000',
                'phone': '+212 5 24 33 44 55',
                'email': 'infos@batirco.ma',
                'website': 'https://www.batirco.ma',
                'is_active': True,
            },
            {
                'code': 'DEMO-FIDUC-04',
                'name': 'Fiduciaire Fès Expertise',
                'type': 'PRIVATE',
                'legal_id': 'RC-20987-FES',
                'address': '12 Rue de la Liberté, Fès 30000',
                'phone': '+212 5 35 62 33 44',
                'email': 'contact@fiduciairefes.ma',
                'website': 'https://www.fiduciairefes.ma',
                'is_active': True,
            },
            {
                'code': 'DEMO-TRANS-05',
                'name': 'TransLog Maroc',
                'type': 'PRIVATE',
                'legal_id': 'RC-55432-TNG',
                'address': '15 Rue Ibn Rochd, Tanger 90000',
                'phone': '+212 5 39 37 15 26',
                'email': 'info@translog.ma',
                'website': 'https://www.translog.ma',
                'is_active': True,
            },
            {
                'code': 'DEMO-ATLAS-06',
                'name': 'Hôtel Atlas Palace',
                'type': 'PRIVATE',
                'legal_id': 'RC-44321-AGD',
                'address': 'Boulevard du 20 Août, Station Balnéaire, Agadir 80000',
                'phone': '+212 5 28 84 56 78',
                'email': 'reservation@atlaspalace.ma',
                'website': 'https://www.atlaspalace.ma',
                'is_active': True,
            },
            {
                'code': 'DEMO-SANTE-07',
                'name': 'Polyclinique Al Amal',
                'type': 'PRIVATE',
                'legal_id': 'RC-76543-CAS',
                'address': '34 Rue Allal Ben Abdellah, Casablanca 20100',
                'phone': '+212 5 22 90 12 34',
                'email': 'contact@polycliniquealamal.ma',
                'website': 'https://www.polycliniquealamal.ma',
                'is_active': True,
            },
            {
                'code': 'DEMO-AGRI-08',
                'name': 'Coopérative Agricole du Saïss',
                'type': 'PRIVATE',
                'legal_id': 'RC-12678-MKN',
                'address': 'Route de Fès, Km 12, Meknès 50000',
                'phone': '+212 5 35 51 23 45',
                'email': 'saiss.coop@agri.ma',
                'website': 'https://www.cooperativesaiss.ma',
                'is_active': False,
            },
            {
                'code': 'DEMO-GREEN-09',
                'name': 'GreenEnergy Maroc',
                'type': 'PRIVATE',
                'legal_id': 'RC-88765-OUJ',
                'address': 'Parc Industriel Technopolis, Rabat 10100',
                'phone': '+212 5 37 77 88 99',
                'email': 'info@greenenergy.ma',
                'website': 'https://www.greenenergy.ma',
                'is_active': True,
            },
            {
                'code': 'DEMO-SHOP-10',
                'name': 'MegaStore E-Commerce',
                'type': 'PRIVATE',
                'legal_id': 'RC-33456-MRK',
                'address': 'Angle Avenue Yacoub El Mansour, Marrakech 40050',
                'phone': '+212 5 24 44 55 66',
                'email': 'service@megastore.ma',
                'website': 'https://www.megastore.ma',
                'is_active': False,
            },
            # ===== PUBLIC (10) =====
            {
                'code': 'DEMO-MS-11',
                'name': 'Ministère de la Santé et de la Protection Sociale',
                'type': 'PUBLIC',
                'legal_id': 'Décret n° 2-95-405',
                'address': '335 Avenue Mohammed V, Rabat 10000',
                'phone': '+212 5 37 76 61 00',
                'email': 'contact@sante.gov.ma',
                'website': 'https://www.sante.gov.ma',
                'is_active': True,
            },
            {
                'code': 'DEMO-CR-12',
                'name': 'Conseil Régional de Casablanca-Settat',
                'type': 'PUBLIC',
                'legal_id': 'Décret n° 2-15-783',
                'address': 'Boulevard Zerktouni, Casablanca 20000',
                'phone': '+212 5 22 43 21 00',
                'email': 'contact@regioncasablancasettat.ma',
                'website': 'https://www.regioncasablancasettat.ma',
                'is_active': True,
            },
            {
                'code': 'DEMO-COMM-13',
                'name': 'Commune Urbaine de Marrakech',
                'type': 'PUBLIC',
                'legal_id': 'Arrêté n° 12-2020',
                'address': 'Place de la Liberté, Marrakech 40000',
                'phone': '+212 5 24 38 80 00',
                'email': 'contact@marrakech.ma',
                'website': 'https://www.marrakech.ma',
                'is_active': True,
            },
            {
                'code': 'DEMO-UNIV-14',
                'name': 'Université Sidi Mohamed Ben Abdellah',
                'type': 'PUBLIC',
                'legal_id': 'Décret n° 2-75-663',
                'address': 'Route d\'Immouzer, B.P. 2626, Fès 30000',
                'phone': '+212 5 35 60 18 00',
                'email': 'presidence@usmba.ac.ma',
                'website': 'https://www.usmba.ac.ma',
                'is_active': True,
            },
            {
                'code': 'DEMO-JUST-15',
                'name': 'Tribunal Administratif de Rabat',
                'type': 'PUBLIC',
                'legal_id': 'Loi n° 41-90',
                'address': 'Avenue de la Victoire, Rabat 10000',
                'phone': '+212 5 37 72 10 10',
                'email': 'greffe@tarabat.justice.ma',
                'website': 'https://www.tribunaux.ma',
                'is_active': True,
            },
            {
                'code': 'DEMO-PORT-16',
                'name': 'Agence Nationale des Ports – Tanger Med',
                'type': 'PUBLIC',
                'legal_id': 'Décret n° 2-06-103',
                'address': 'Zone Portuaire Tanger Med, Tanger 91000',
                'phone': '+212 5 39 37 80 00',
                'email': 'contact@anp.org.ma',
                'website': 'https://www.anp.org.ma',
                'is_active': True,
            },
            {
                'code': 'DEMO-PARC-17',
                'name': 'Parc National d\'Ifrane – Direction Régionale',
                'type': 'PUBLIC',
                'legal_id': 'Décret n° 2-04-782',
                'address': 'Avenue Hassan II, Ifrane 53000',
                'phone': '+212 5 35 56 60 20',
                'email': 'pn.ifrane@eauxetforets.gov.ma',
                'website': 'https://www.eauxetforets.gov.ma',
                'is_active': False,
            },
            {
                'code': 'DEMO-ONEE-18',
                'name': 'Office National de l\'Électricité et de l\'Eau Potable',
                'type': 'PUBLIC',
                'legal_id': 'Loi n° 40-09',
                'address': '65 Rue Othmane Ibn Affane, Casablanca 20000',
                'phone': '+212 5 22 66 80 00',
                'email': 'relationclient@onee.ma',
                'website': 'https://www.onee.ma',
                'is_active': True,
            },
            {
                'code': 'DEMO-CHU-19',
                'name': 'Centre Hospitalier Universitaire Mohammed VI',
                'type': 'PUBLIC',
                'legal_id': 'Décret n° 2-08-745',
                'address': 'Route de Sidi Bel Abbès, Oujda 60000',
                'phone': '+212 5 36 50 80 00',
                'email': 'contact@chuoujda.ma',
                'website': 'https://www.chuoujda.ma',
                'is_active': True,
            },
            {
                'code': 'DEMO-AGRIPUB-20',
                'name': 'Direction Provinciale de l\'Agriculture de Meknès',
                'type': 'PUBLIC',
                'legal_id': 'Décret n° 2-12-340',
                'address': 'Avenue des FAR, Meknès 50000',
                'phone': '+212 5 35 52 45 00',
                'email': 'dpa.meknes@agriculture.gov.ma',
                'website': 'https://www.agriculture.gov.ma',
                'is_active': False,
            },
        ]

        created = 0
        for data in orgs:
            if Organization.all_objects.filter(code=data['code']).exists():
                continue
            Organization.objects.create(
                **data,
                is_test_data=True,
                created_by=None,
            )
            created += 1

        self.stdout.write(self.style.SUCCESS(f'✅ {created} organisations de démo créées'))
