# Generated by Django 4.2.30 on 2026-07-06 18:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0019_alter_customuser_platform_role_alter_membership_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé (logique)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('numero_sd_affaire', models.PositiveIntegerField(help_text="Numéro d'ordre dans la propriété mère", verbose_name="Numéro du SD d'affaire")),
                ('nature_procedure_affaire', models.CharField(choices=[('IFF', 'Immatriculation Foncière Facultative'), ('IFE', "Immatriculation Foncière d'Ensemble"), ('IFR', 'Immatriculation Foncière de Remembrement'), ('PS_FORET', 'Procédure spéciale Forêt'), ('PS_COLLECTIF', 'Procédure spéciale Collectif'), ('PS_EXPROPRIATION', 'Procédure spéciale Expropriation'), ('AS', 'Affaires subséquentes')], max_length=20, verbose_name='Nature de procédure')),
                ('nature_affaire', models.CharField(choices=[('BI', "Bornage d'immatriculation"), ('BC', 'Bornage complémentaire'), ('IFE', "Immatriculation Foncière d'Ensemble"), ('IFR', 'Immatriculation Foncière de Remembrement'), ('RB', 'Recollement de bornage'), ('MEC', 'Mise en Concordance'), ('MT', 'Morcellement'), ('FS', 'Fusion'), ('MT-FS', 'Morcellement-Fusion'), ('LOT', 'Lotissement'), ('COP', 'Copropriété')], max_length=10, verbose_name="Nature d'affaire")),
                ('date_bornage', models.DateField(blank=True, help_text='Requise pour IFF/AS/PS_* ; non définie pour IFE/IFR', null=True, verbose_name='Date de bornage / recollement')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Affaire (SD)',
                'verbose_name_plural': 'Affaires (SD)',
                'ordering': ['numero_sd_affaire'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé (logique)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('nom_projet', models.CharField(max_length=255, verbose_name='Nom du projet')),
                ('description_projet', models.TextField(blank=True, verbose_name='Description')),
                ('code_projet', models.CharField(db_index=True, help_text='Identifiant court unique du projet', max_length=50, unique=True, verbose_name='Code projet')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_cours', 'En cours'), ('cloture', 'Clôturé'), ('archive', 'Archivé')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projets', to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ssdgps',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé (logique)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('nature_ssdgps', models.CharField(choices=[('PDC/GPS', 'Projet de densification cadastrale par GPS'), ('DDC/GPS', 'Dossier de densification cadastrale par GPS'), ('PLC/GPS', 'Projet de levé cadastral par GPS'), ('DLC/GPS', 'Dossier de levé cadastral par GPS')], max_length=10, verbose_name='Nature du SSDGPS')),
                ('numero_ssdgps', models.PositiveIntegerField(help_text="Numéro d'ordre dans le SD d'affaire mère", verbose_name='Numéro du SSDGPS')),
                ('type_ssdgps', models.CharField(choices=[('mono-session', 'Mono-session'), ('multi-session', 'Multi-session')], default='mono-session', max_length=15, verbose_name='Type du SSDGPS')),
                ('affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssdgps_set', to='projects.affaire', verbose_name='Affaire (SD)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'SSDGPS',
                'verbose_name_plural': 'SSDGPS',
                'ordering': ['numero_ssdgps'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé (logique)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('numero_session', models.PositiveIntegerField(verbose_name='Numéro de session')),
                ('date_session', models.DateField(blank=True, null=True, verbose_name='Date de la session')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('ssdgps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='projects.ssdgps', verbose_name='SSDGPS')),
            ],
            options={
                'verbose_name': 'Session GPS',
                'verbose_name_plural': 'Sessions GPS',
                'ordering': ['numero_session'],
            },
        ),
        migrations.CreateModel(
            name='Propriete',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé (logique)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('nom_propriete', models.CharField(max_length=255, verbose_name='Propriété-dite')),
                ('id_requisition', models.CharField(blank=True, help_text='Ex. R19000/55', max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^R\\d{1,6}/(?:\\d{1,4}|[A-Z]{1,2})$'), 'Format attendu : R<numéro>/<indice>.')], verbose_name='Réquisition')),
                ('id_titre', models.CharField(blank=True, help_text='Ex. T12345/A', max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^T\\d{1,6}/(?:\\d{1,4}|[A-Z]{1,2})$'), 'Format attendu : T<numéro>/<indice>.')], verbose_name='Titre foncier')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprietes', to='projects.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Propriété',
                'verbose_name_plural': 'Propriétés',
                'ordering': ['nom_propriete'],
            },
        ),
        migrations.AddField(
            model_name='affaire',
            name='propriete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affaires', to='projects.propriete', verbose_name='Propriété'),
        ),
        migrations.AddConstraint(
            model_name='ssdgps',
            constraint=models.UniqueConstraint(fields=('affaire', 'numero_ssdgps'), name='unique_numero_ssdgps_par_affaire'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('ssdgps', 'numero_session'), name='unique_numero_session_par_ssdgps'),
        ),
        migrations.AddIndex(
            model_name='projet',
            index=models.Index(fields=['organization', 'is_deleted'], name='projects_pr_organiz_3a6529_idx'),
        ),
        migrations.AddConstraint(
            model_name='affaire',
            constraint=models.UniqueConstraint(fields=('propriete', 'numero_sd_affaire'), name='unique_numero_sd_par_propriete'),
        ),
    ]
