# Generated by Django 4.2.30 on 2026-07-15 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organismes', '0001_initial'),
        ('projects', '0004_affaire_deleted_by_affaire_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriete',
            name='organisme_niveau1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proprietes', to='organismes.organismeniveau1', verbose_name='Organisme de premier niveau'),
        ),
        migrations.AddField(
            model_name='propriete',
            name='organisme_niveau2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proprietes', to='organismes.organismeniveau2', verbose_name='Organisme de deuxième niveau'),
        ),
    ]
