# Generated by Django 4.2.30 on 2026-07-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_propriete_organisme_niveau1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affaire',
            name='date_bornage',
            field=models.DateTimeField(blank=True, help_text='Requise pour IFF/AS/PS_* ; non définie pour IFE/IFR. Horodatage complet (jj/mm/aaaa hh:mm:ss).', null=True, verbose_name='Date et heure de bornage / recollement'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date_session',
            field=models.DateTimeField(blank=True, help_text='Horodatage complet (jj/mm/aaaa hh:mm:ss).', null=True, verbose_name='Date et heure de la session'),
        ),
    ]
