# Generated by Django 4.2.30 on 2026-07-15 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganismeNiveau1',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text="Identifiant court unique de l'organisme (ex. ANCFCC, SCA-AZILAL).", max_length=50, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom officiel')),
                ('sigle', models.CharField(blank=True, max_length=50, verbose_name='Sigle / abréviation')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé (logique)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Organisme de premier niveau',
                'verbose_name_plural': 'Organismes de premier niveau',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='OrganismeNiveau2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text="Identifiant court unique de l'organisme (ex. ANCFCC, SCA-AZILAL).", max_length=50, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom officiel')),
                ('sigle', models.CharField(blank=True, max_length=50, verbose_name='Sigle / abréviation')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé (logique)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('ville', models.CharField(blank=True, max_length=120, verbose_name='Ville / province')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
                ('niveau1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='niveaux2', to='organismes.organismeniveau1', verbose_name='Organisme de premier niveau')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Organisme de deuxième niveau',
                'verbose_name_plural': 'Organismes de deuxième niveau',
                'ordering': ['nom'],
                'indexes': [models.Index(fields=['is_deleted'], name='organismes__is_dele_a25ce9_idx'), models.Index(fields=['code'], name='organismes__code_c2e30d_idx'), models.Index(fields=['niveau1'], name='organismes__niveau1_0d3d4b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='organismeniveau1',
            index=models.Index(fields=['is_deleted'], name='organismes__is_dele_33ba59_idx'),
        ),
        migrations.AddIndex(
            model_name='organismeniveau1',
            index=models.Index(fields=['code'], name='organismes__code_854431_idx'),
        ),
    ]
