# Generated by Django 4.2 on 2026-07-20 20:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name="Horodatage de l'instantané")),
                ('is_backfill', models.BooleanField(default=False, verbose_name='Reconstruit (historique estimé)')),
                ('total_bytes', models.BigIntegerField(default=0, verbose_name='Octets totaux')),
                ('total_files', models.PositiveIntegerField(default=0, verbose_name='Nombre de fichiers')),
                ('by_type', models.JSONField(blank=True, default=dict, verbose_name='Par nature de fichier')),
                ('by_organization', models.JSONField(blank=True, default=dict, verbose_name='Par organisation')),
                ('by_project', models.JSONField(blank=True, default=dict, verbose_name='Par projet')),
                ('by_user', models.JSONField(blank=True, default=dict, verbose_name='Par utilisateur')),
            ],
            options={
                'verbose_name': 'Instantané de stockage',
                'verbose_name_plural': 'Instantanés de stockage',
                'ordering': ['-taken_at'],
            },
        ),
    ]
