# Generated by Django 4.2 on 2026-07-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagesnapshot',
            name='by_role',
            field=models.JSONField(blank=True, default=dict, verbose_name='Par rôle applicatif'),
        ),
    ]
