# Generated by Django 4.2.30 on 2026-07-07 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pieces.models
import pieces.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_affaire_deleted_by_affaire_updated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé (logique)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('type_piece', models.CharField(choices=[('PGSDGPS', 'Page de Garde SDGPS'), ('RDC', 'Rapport de Consultation'), ('LPA', 'Liste des Points Anciens'), ('CCSPA', 'Canevas de Contrôle de Stabilité des Points Anciens'), ('CDC', 'Canevas de Densification Cadastrale'), ('CLC', 'Canevas de Levé Cadastral'), ('PPA', 'Photos des points anciens'), ('PPN', 'Photos des points nouveaux'), ('FTR', 'Fiche Technique des Récepteurs'), ('ROB', 'Rapport des Observations Brutes'), ('RTLB', 'Rapport du traitement des lignes de base'), ('RFB', 'Rapport des fermetures des Boucles'), ('RDL', 'Rapport de la détermination libre'), ('RDN', 'Rapport de la détermination N°k'), ('RDI', 'Rapport des déterminations Intermédiaires'), ('RDD', 'Rapport de la détermination définitive'), ('RC', 'Rapport de contrôle')], max_length=10, verbose_name='Type de pièce')),
                ('numero', models.PositiveSmallIntegerField(blank=True, help_text='Requis uniquement pour les types répétables (RDN n°1, 2, 3…)', null=True, verbose_name='Numéro (types répétables, ex. RDN)')),
                ('fichier', models.FileField(blank=True, null=True, upload_to=pieces.models.piece_upload_path, validators=[pieces.validators.validate_piece_file_extension, pieces.validators.validate_piece_file_size], verbose_name='Fichier (image ou document source)')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Données structurées')),
                ('source_saisie', models.CharField(choices=[('manuel', 'Saisie manuelle'), ('import', 'Import CSV/Excel'), ('image', 'Upload image'), ('ui', 'Généré automatiquement')], max_length=10, verbose_name='Source de saisie')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validée'), ('rejete', 'Rejetée')], default='brouillon', max_length=10, verbose_name='Statut')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='projects.session', verbose_name='Session')),
                ('ssdgps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='projects.ssdgps', verbose_name='SSDGPS')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Pièce',
                'verbose_name_plural': 'Pièces',
                'ordering': ['type_piece', 'numero'],
            },
        ),
        migrations.AddConstraint(
            model_name='piece',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('session__isnull', True), ('ssdgps__isnull', False)), models.Q(('session__isnull', False), ('ssdgps__isnull', True)), _connector='OR'), name='piece_exactly_one_parent'),
        ),
        migrations.AddConstraint(
            model_name='piece',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('ssdgps__isnull', False)), fields=('ssdgps', 'type_piece', 'numero'), name='unique_piece_type_numero_par_ssdgps'),
        ),
        migrations.AddConstraint(
            model_name='piece',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('session__isnull', False)), fields=('session', 'type_piece', 'numero'), name='unique_piece_type_numero_par_session'),
        ),
    ]
