# Generated by Django 4.2.30 on 2026-07-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='ordre',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre dans le rapport'),
        ),
    ]
