# Generated by Django 4.2 on 2026-07-09 17:52

from django.db import migrations, models
import django.db.models.deletion
import pieces.models
import pieces.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0004_alter_piece_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.ImageField(upload_to=pieces.models.piece_image_upload_path, validators=[pieces.validators.validate_piece_image_extension, pieces.validators.validate_piece_file_size, pieces.validators.validate_image_content], verbose_name='Fichier image')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre dans la galerie')),
                ('format', models.CharField(blank=True, max_length=10, verbose_name='Format')),
                ('taille_octets', models.PositiveIntegerField(default=0, verbose_name='Taille (octets)')),
                ('largeur', models.PositiveIntegerField(default=0, verbose_name='Largeur (px)')),
                ('hauteur', models.PositiveIntegerField(default=0, verbose_name='Hauteur (px)')),
                ('mode_couleur', models.CharField(blank=True, max_length=20, verbose_name="Type d'image")),
                ('compression', models.CharField(blank=True, max_length=40, verbose_name='Compression')),
                ('date_creation', models.DateTimeField(blank=True, null=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(blank=True, null=True, verbose_name='Date de dernière modification')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ajoutée le')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pieces.piece', verbose_name='Pièce')),
            ],
            options={
                'verbose_name': 'Image de pièce',
                'verbose_name_plural': 'Images de pièce',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
