# Generated by Django 4.2 on 2026-07-09 18:13

from django.db import migrations, models
import pieces.models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0005_pieceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieceimage',
            name='apercu',
            field=models.ImageField(blank=True, null=True, upload_to=pieces.models.piece_image_preview_path, verbose_name='Aperçu PNG (formats non affichables, ex. TIFF)'),
        ),
    ]
