# Generated by Django 4.2 on 2026-07-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0006_pieceimage_apercu'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieceimage',
            name='point_ref',
            field=models.CharField(blank=True, max_length=100, verbose_name='Point rattaché'),
        ),
    ]
