# Generated by Django 4.2 on 2026-07-14 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0007_pieceimage_point_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='orientation',
            field=models.CharField(choices=[('auto', 'Automatique'), ('portrait', 'Portrait'), ('paysage', 'Paysage')], default='auto', help_text='AUTO : orientation calculée automatiquement selon la largeur des données ; sinon force le portrait ou le paysage pour le contenu de la pièce.', max_length=10, verbose_name='Orientation (rapport PDF)'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='type_piece',
            field=models.CharField(choices=[('PGSDGPS', 'Page de Garde SDGPS'), ('RDC', 'Rapport de Consultation'), ('LPA', 'Liste des Points Anciens'), ('CCSPA', 'Canevas de Contrôle de Stabilité des Points Anciens'), ('CDC', 'Canevas de Densification Cadastrale'), ('CLC', 'Canevas de Levé Cadastral'), ('PPA', 'Photos des points anciens'), ('PPN', 'Photos des points nouveaux'), ('FTR', 'Fiche Technique des Récepteurs'), ('ROB', 'Rapport des Observations Brutes'), ('RTLB', 'Rapport du traitement des lignes de base'), ('RFB', 'Rapport des fermetures des Boucles'), ('RDL', 'Rapport de la détermination libre'), ('RDN', 'Rapport de la détermination N°k'), ('RDIA', 'Rapport des déterminations intermédiaires'), ('RDI', 'Rapport des déterminations Intermédiaires'), ('RDD', 'Rapport de la détermination définitive'), ('RC', 'Rapport de contrôle')], max_length=10, verbose_name='Type de pièce'),
        ),
    ]
