# Generated by Django 4.2.30 on 2026-07-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0008_piece_orientation_alter_piece_type_piece'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='versions_rapport',
            field=models.CharField(choices=[('brut', 'Version brute'), ('ecarts', 'Version des écarts'), ('both', 'Les deux versions')], default='both', help_text='Rapports de détermination : afficher la version brute des données, la version des écarts par rapport à la détermination définitive, ou les deux.', max_length=10, verbose_name='Versions affichées (RDL/RDN/RDIA)'),
        ),
    ]
