# Generated by Django 4.2.30 on 2026-07-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0009_piece_versions_rapport'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceFieldMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_piece', models.CharField(choices=[('PGSDGPS', 'Page de Garde SDGPS'), ('RDC', 'Rapport de Consultation'), ('LPA', 'Liste des Points Anciens'), ('CCSPA', 'Canevas de Contrôle de Stabilité des Points Anciens'), ('CDC', 'Canevas de Densification Cadastrale'), ('CLC', 'Canevas de Levé Cadastral'), ('PPA', 'Photos des points anciens'), ('PPN', 'Photos des points nouveaux'), ('FTR', 'Fiche Technique des Récepteurs'), ('ROB', 'Rapport des Observations Brutes'), ('RTLB', 'Rapport du traitement des lignes de base'), ('RFB', 'Rapport des fermetures des Boucles'), ('RDL', 'Rapport de la détermination libre'), ('RDN', 'Rapport de la détermination N°k'), ('RDIA', 'Rapport des déterminations intermédiaires'), ('RDI', 'Rapport des déterminations Intermédiaires'), ('RDD', 'Rapport de la détermination définitive'), ('RC', 'Rapport de contrôle')], max_length=10, verbose_name='Type de pièce')),
                ('field_name', models.CharField(max_length=100, verbose_name='Nom technique du champ')),
                ('description', models.TextField(blank=True, help_text="Consistance exacte du champ et à quoi il correspond (aide à l'import).", verbose_name='Description détaillée')),
                ('tooltip', models.CharField(blank=True, help_text='Résumé court affiché en infobulle.', max_length=255, verbose_name='Infobulle')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Description de champ de pièce',
                'verbose_name_plural': 'Descriptions de champs de pièces',
                'ordering': ['type_piece', 'field_name'],
                'unique_together': {('type_piece', 'field_name')},
            },
        ),
    ]
