# Generated by Django 4.2.30 on 2026-07-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0010_piecefieldmeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_piece', models.CharField(choices=[('PGSDGPS', 'Page de Garde SDGPS'), ('RDC', 'Rapport de Consultation'), ('LPA', 'Liste des Points Anciens'), ('CCSPA', 'Canevas de Contrôle de Stabilité des Points Anciens'), ('CDC', 'Canevas de Densification Cadastrale'), ('CLC', 'Canevas de Levé Cadastral'), ('PPA', 'Photos des points anciens'), ('PPN', 'Photos des points nouveaux'), ('FTR', 'Fiche Technique des Récepteurs'), ('ROB', 'Rapport des Observations Brutes'), ('RTLB', 'Rapport du traitement des lignes de base'), ('RFB', 'Rapport des fermetures des Boucles'), ('RDL', 'Rapport de la détermination libre'), ('RDN', 'Rapport de la détermination N°k'), ('RDIA', 'Rapport des déterminations intermédiaires'), ('RDI', 'Rapport des déterminations Intermédiaires'), ('RDD', 'Rapport de la détermination définitive'), ('RC', 'Rapport de contrôle')], max_length=10, verbose_name='Type de pièce')),
                ('name', models.CharField(max_length=100, verbose_name='Nom technique (identifiant de colonne)')),
                ('label', models.CharField(max_length=150, verbose_name='Libellé affiché')),
                ('field_type', models.CharField(choices=[('text', 'Texte'), ('number', 'Nombre'), ('date', 'Date'), ('textarea', 'Texte long')], default='text', max_length=10, verbose_name='Type de donnée')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre (après les champs du catalogue)')),
            ],
            options={
                'verbose_name': 'Champ personnalisé de pièce',
                'verbose_name_plural': 'Champs personnalisés de pièces',
                'ordering': ['type_piece', 'ordre', 'id'],
                'unique_together': {('type_piece', 'name')},
            },
        ),
    ]
