# Generated by Django 4.2.30 on 2026-07-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0012_seed_field_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecefieldmeta',
            name='required',
            field=models.BooleanField(default=False, help_text="Champ verrouillé dans la vue « Import des données » : toujours importé, non désactivable par l'opérateur (indispensable aux calculs).", verbose_name='Champ obligatoire'),
        ),
    ]
