# Generated by Django 4.2 on 2026-07-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0014_seed_required_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='taille_octets',
            field=models.PositiveIntegerField(default=0, verbose_name='Taille du fichier (octets)'),
        ),
    ]
